Request for Code Review: Building with Backgrounds & Gradients
edieatha/apple pull request #1
Opened 2020-04-13 14:50 UTC by edieatha

## Apple Page Clone:
1. Used background image for header image.
2. Applied a gradient on navigation buttons.
3. Used positioning 'absolute' on all sections of the page.
4. Aligned footer and aside elements with flex.
5. Added images and text styles.

2020-04-13 23:11 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-13 23:27 UTC, mikenath223 requested changes
### Hello @edieatha  👋

You've done quite well on this.
The project looks quite good to go, but for a few changes.

Kindly make the following changes.

- [ ] Required - As this project is focused on backgrounds and gradients, please make **CONVERT** image elements in the project to backgrounds. 

- [x] Required - Also the search input is expected to be a form input field. Kindly change this, and assign the search icon as a background too.
![ice_screenshot_20200414-001446](https://user-images.githubusercontent.com/33323077/79170091-3f874080-7de6-11ea-9d77-96e9e5bcc0c6.png)

- [x] Required - Kindly change the images you have in the screenshot below👇 into text elements. You should make them text elements in the project.
![ice_screenshot_20200414-001855](https://user-images.githubusercontent.com/33323077/79170193-8e34da80-7de6-11ea-92c8-5580c63c4809.png)

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-13 23:30 UTC, mikenath223 commented on index.html
> +
Convert these image elements to text elements instead.

2020-04-13 23:30 UTC, mikenath223 commented on index.html
> +		</div>
Convert the images here also to text elements

2020-04-13 23:32 UTC, mikenath223 commented on index.html
> +            </form>
Kindly change this into a search input field. Also fix the HTML validation errors in the HTML code with this [tool](https://validator.w3.org/nu/#file).

2020-04-14 17:36 UTC, edieatha commented
## TSE Code Review Changes

1. Converted image elements in HTML to background CSS elements.
2. Changed search element to input type element
3. Changed text images to actual text elements
4. Validated HTML

2020-04-15 00:02 UTC, mikenath223 approved these changes
### CONGRATULATIONS  @edieatha  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**

Don't forget to fill the project completion form👍
Good luck with the next project.

HAPPY CODING👨‍💻

2020-04-27 16:21 UTC, merged